# Use an official lightweight Python image as the base
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application code to the container
COPY hello.py /app

# Define the command to run the application
CMD ["python", "hello.py"]
